[package]
name = "subdomain-finder"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
trust-dns-resolver = { version = "0.23", features = ["tokio-runtime"] }
colored = "2"
futures = "0.3"

figlet-rs = "0.1.5"
serde_json = "1.0.140"



